# AVID
# Automated workflow system for cohort analysis in radiology and radiation therapy
#
# Copyright (c) German Cancer Research Center,
# Software development for Integrated Diagnostic and Therapy (SIDT).
# All rights reserved.
#
# This software is distributed WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.
#
# See LICENSE.txt or http://www.dkfz.de/en/sidt/index.html for details.

from builtins import object
class LinkerBase(object):
  ''' Linkers serve as delegate to generate sub selection that have some semantic
      linkage (e.g. have the same case id or time point) to the master artefacts
      split (list of artefact; e.g. generated by splitter)
  '''
  def __init__(self):
    pass
      
  def getLinkedSelection(self, primaryIndex, primarySelections, secondarySelections):
    ''' Get the sub selections (splits)  of slave that has a meaningful semantic link
        to the master selection/index. The default implementation just passes through
        the secondarySelection (so everything gets linked).
        @result List of all linked artefacts. Therefore all artefacts from slave selection
        that fullfill the link criterion in respect to the master artefact.
        @param primaryIndex index of the entry in the primarySelections that is defining
        for the link.
        @param primarySelections the master selection that contains the master entry
        @param secondarySelections that is used to generate the subset. '''
    return secondarySelections

  def __add__(self,other):
    ''' Creates an AndLinker with both operands.'''
    andLinker = AndLinker(self,other)
    return andLinker


class AndLinker(LinkerBase):
  '''
      Special linker that works like an and operation on to child linkers.
      The selection result of the AndLinker is the intersection of the selection
      of both child linkers.
  '''
  def __init__(self, linker1, linker2):
    ''' init '''
    self._linker1 = linker1
    self._linker2 = linker2

  def getLinkedSelection(self, primaryIndex, primarySelections, secondarySelection):
    '''Filters the given list of entries and returns all selected entries'''
    selections1 = self._linker1.getLinkedSelection(primaryIndex, primarySelections, secondarySelection)
    selections2 = self._linker2.getLinkedSelection(primaryIndex, primarySelections, secondarySelection)
    resultSelections = list(dict(),)
    for item1 in selections1:
      for item2 in selections2:
        if item1 == item2:
          resultSelections.append(item1)
          selections2.remove(item2)
          break
          
    return resultSelections


from .keyValueLinker import KeyValueLinker
from .keyValueLinker import CaseLinker
from .keyValueLinker import TimePointLinker
from .fractionLinker import FractionLinker
from .caseInstanceLinker import CaseInstanceLinker