default:
  image: python:3.9
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip

stages:
  - build
  - test
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

build:
  stage: build
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - pip install dist/*.whl
    - python -m unittest

publish:
  stage: publish
  script:
    - pip install twine
    - TWINE_PASSWORD=${PyPI_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/*
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "master"
